### ISSUE TITLE
Private Key redeem

### ISSUE THREAD

**Issue by antonio-fr** [greenaddress/WalletCrx#18]
After multiple tries, import a WIF private key is not working.
Private key sweep is not working, even after more than 6 confirmations. Wheel spins then Sweep text appears again on button after seconds.

TypeError: Cannot read property '0' of undefined
    at controllers.js:58
    at angular.min.js:119
    at r.$eval (angular.min.js:133)
    at r.$digest (angular.min.js:130)
    at r.$apply (angular.min.js:134)
    at r.$rootScope.safeApply (app.js:63)
    at services.js:1911(anonymous function) @ angular.min.js:107(anonymous function) @ app.js:112(anonymous function) @ angular.min.js:119r.$eval @ angular.min.js:133r.$digest @ angular.min.js:130r.$apply @ angular.min.js:134$rootScope.safeApply @ app.js:63(anonymous function) @ services.js:1911
23trezor.js:36 devices =

**Comment by greenaddress** [comment]
This is a known problem, should be fixed by a server update (it's caused by the client timing out on the utxo history of a WIF)

**Comment by greenaddress** [comment]
This should now be fixed. @antonio-fr  please reopen if you have any trouble. It should now work on both testnet and mainnet.

**Comment by antonio-fr** [comment]
Nop sorry , this is the same, doesn't seem to be fixed.

**Comment by antonio-fr** [comment]
Sorry, still not fixed, I will open a new issue related to that.
